import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Box, Button, Link, Text, Image, Input } from '@chakra-ui/react';
import { useContext, useState } from 'react';
import { languageContext } from './_app';
import { JapaneseIntroduceCard } from './JapaneseIntroduceCard';
import { RoundIcon } from '../components/ui_parts/RoundIcon';
import { EnglishIntroduceCard } from "./EnglishIntroduceCard";
import { WaveText } from "./WaveText";

const Home: NextPage = () => {
    const {selectedLanguage} = useContext(languageContext);

    const reactContent = () => (<Text
            width={'150px'}
            mt={'15px'}
            fontWeight={'600'}
            color={'#121212b8'}
            fontSize={'14px'}
        >
            実務経験あり。ポートフォリオのソースコードは
            <Link fontWeight={'900'} color={'black'}>
                こちら。
            </Link>
        </Text>
    )

    const Icons = [
        {
            title: 'React',
            imgSrc: '/skill/react.png',
            padding: 15,
            content: reactContent(),
        },
        {title: 'Vue3', imgSrc: '/skill/vue.png', padding: 15, sentence: "TypeScript,CompositionAPI,Piniaを用いての実務経験あり。"},
        {title: 'Angular', imgSrc: '/skill/angular.png', padding: 15, sentence: "実務経験あり。JSフレームワークの基礎はAngularで学びました。"},
        {title: 'NestJS', imgSrc: '/skill/nest.svg', padding: 15, sentence: "個人開発でのTypeORM,GraphQL実装経験あり。"},
        {title: 'Rails',imgSrc:'skill/rails.png',padding:15, sentence:"Rails6の実務経験あり。"},
        {title:'Terraform',imgSrc:'skill/Terraform.png',padding:15,sentence:"実務でのECSコード化経験あり"},
        {
            title: "AWS",
            imgSrc: '/skill/aws.png',
            padding: 5,
            sentence:
                'AWSソリューションアーキテクト保有(ECS,EC2,Lambda,Route53,CodeBuild,CloudFront,S3等の経験あり)',
        },
    ];



    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app'/>
                <link rel='icon' href='/favicon.ico'/>
            </Head>
            <main className={styles.main}>
                {selectedLanguage === 'ja' ? (
                    <JapaneseIntroduceCard
                        position={'Webエンジニア'}
                        name={'真野 笑馬'}
                        englishName={'Shoma Mano'}
                    ></JapaneseIntroduceCard>
                ) : <EnglishIntroduceCard></EnglishIntroduceCard>}
                <WaveText text={"Welcome To My Portforio"}></WaveText>
                <Text mt={'40px'} fontSize={'30px'} fontWeight={'700'}>
                    スキル
                </Text>
                <Text mt={'10px'}>フロントからバックエンド、インフラまで経験あり</Text>
                <Box
                    mt={'20px'}
                    justifyItems={'center'}
                    width={'70%'}
                    gridGap={'30px'}
                    display={'grid'}
                    gridTemplateColumns={'repeat(auto-fit,minmax(150px,1fr))'}
                >
                    {Icons.map((v) => (
                        <Box
                            key={v.imgSrc}
                            display={'flex'}
                            flexDirection={'column'}
                            alignItems={'center'}
                        >
                            <Text wordBreak={'break-all'} fontWeight={"700"} mb={"7px"} textAlign={"center"}>{v.title}</Text>
                            <RoundIcon imgSrc={v.imgSrc} padding={v.padding}></RoundIcon>
                            <Box width={'100%'}>
                                <Text
                                    width={'150px'}
                                    mt={'15px'}
                                    fontWeight={'600'}
                                    color={'#121212b8'}
                                    fontSize={'14px'}
                                >
                                    {v.sentence}
                                </Text>
                                {v.content}
                            </Box>
                        </Box>
                    ))}
                </Box>
            </main>
        </div>
    );
};

export default Home;
