import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { MyComponent } from "./mycomponent";
import { Box, Button } from "@chakra-ui/react";
import { SideBarContent } from "../components/left_side_bar/SideBarContent";
import { RightSideBar } from "../components/right_side_bar/RightSideBar";
import { ShowCount } from "./ShowCount";
import { useContext, useState } from "react";
import { languageContext } from "./_app";

const Home: NextPage = () => {
  const hello=()=>console.log("hello")
  let [count,setCount]=useState(0)
  const {selectedLanguage}=useContext(languageContext)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <MyComponent name={"shoma"}>inside</MyComponent>
        <Button onClick={()=>setCount(count+1)}>count up{count}</Button>
        <ShowCount count={count} setCount={setCount}></ShowCount>
        {selectedLanguage==="en"?<h1  className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>:<h1 className={styles.title}>
          ようこそ <a href="https://nextjs.org">Next.jsへ!</a>
        </h1>}
        <Box
            position="fixed"
            left={0}
            px={"8"}
            py={"5"}
            w="290px"
            top={0}
            h="100%"
            bg="white"
            boxShadow="xl"
        >
          <SideBarContent onClick={hello}></SideBarContent>
        </Box>
        <Box
            position="fixed"
            right={0}
            p={5}
            w="100px"
            top={0}
            h="100%"
            bg="white"
            boxShadow="md"
        >
          <RightSideBar></RightSideBar>
        </Box>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
